version: "3.8"
services:
  api:
    container_name: api
    build: ./api
    tty: true
    ports:
      - "3005:3005"
    volumes:
      - ./api:/api
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: $DB_NAME
      # POSTGRES_USER: $DB_USER
      # POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - db_store:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_store: